- name: start httpd
  tags: apache
  service:
    name: "{{apache_service}}"
    state: started
    enabled: yes

- name: Change the configurations of the httpd
  tags: edits
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^ServerAdmin"
    line: ServerAdmin something@somewhere.net
  notify: restart_apache
      #register: httpd

